### ISSUE TITLE
https://www.visioncortex.org/visionmagic-docs is broken

### ISSUE THREAD

**Issue by mootari** [visioncortex/visioncortex.github.io#1]
The page https://www.visioncortex.org/visionmagic-docs breaks during hydration. The content may briefly be visible, but will almost immediately be replaced by "Not found".

**Comment by tyt2y3** [comment]
Thank you for your report. It was my bad. I think the page was renamed to `impression-docs` at some point, and I fixed the broken links in [visionmagic](https://github.com/visioncortex/visionmagic) already.

**Comment by mootari** [comment]
Thanks for the quick fix!

*(For posterity: the broken URL appeared on the demo app, in the link "Paper" which has now been replaced with "Article".)*
